### ISSUE TITLE
build time failure using latest commit.

### ISSUE THREAD

**Issue by dkokron** [PARALLELIO/genf90#2]
Building PIO (https://github.com/NCAR/ParallelIO) using the current genf90.pl (51cf29381fcfe791e65e21d7fd6482c4dcf37aa8) results in build time failure on WCOSS2 systems (SLES-15sp3).  I've tested this with pio-2.5.7, pio-2.5.10 and pio-2.6.2.

pio-2.6.2/src/flib/pionfput_mod.F90.in(157): error #6683: A kind type parameter must be a compile-time constant.   [I8]
    integer(i8), intent(in) :: ival
------------^

Rolling back to genf90.pl commit 5b84bd93bdd0d4bae011ec99be386a81f4ad9ef2 resolves the issue.

**Comment by jedwards4b** [comment]
Using the latest ParallelIO [6539ef0](https://github.com/NCAR/ParallelIO/commit/6539ef05ae7584ec570a56fdab9f7dfb336c2b80) also works.

**Comment by dkokron** [comment]
Are you saying that ParallelIO 6539ef05 using the latest genf90.pl works for you?  That combo fails for me too.

**Comment by jedwards4b** [comment]
I've verified what you are seeing however the genf90 version is set to the correct tag in src/flib/CMakeLists.txt so how are you getting the version mismatches and testing versions I have not yet tagged for release?

**Comment by dkokron** [comment]
Our scripting to build PIO (https://github.com/NOAA-EMC/hpc-stack/blob/nco-wcoss2/libs/build_pio.sh) simply does a clone of the genf90 and CMake_Fortran_utils repositories and uses them without checking out a branch or tag.

**Comment by jedwards4b** [comment]
Hmm so NOAA-EMC is defeating my attempt to align the requirements of the two repositories - this is a NOAA-EMC problem, not a parallelio one.

**Comment by dkokron** [comment]
I would appear so.  Which version of genf90 do you recommend we use?

**Comment by jedwards4b** [comment]
This is documented in file src/flib/CMakeLists.txt, for pio2.6.2 it is set to  GIT_TAG genf90_200608

**Comment by dkokron** [comment]
Thanks!
